backend:
  name: git-gateway

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "products"
    label: "Productos"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Nombre", name: "title", widget: "string"}
      - {label: "Descripción", name: "description", widget: "text"}
      - {label: "Precio (€)", name: "price", widget: "number"}
      - {label: "Imagen", name: "image", widget: "image"}
