backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

site_url: "https://keen-sherbet-d2ced4.netlify.app"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Product Name", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Price", name: "price", widget: "string"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Category", name: "category", widget: "string"}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Us"
        name: "about"
        file: "about.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

      - label: "Contact"
        name: "contact"
        file: "contact.html"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
