backend:
    name: github
  repo: baderclaudia97-bit/maxfood3
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: auth

media_folder: "static/uploads"
public_folder: "/static/uploads"

collections:
  - name: "products"
    label: "Products"
    folder: "content/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float", required: false }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Image", name: "image", widget: "image", required: false }
      - { label: "Published", name: "published", widget: "boolean", default: true }
